version: "3.9"
services:
    translation:
        hostname: translation
        container_name: translation
        build:
            context: .
            dockerfile: Translation/Dockerfile
        ports:
            - "4100:4100/udp"
            - "5001:5001"
            - "5002:5002"
    relay:
        hostname: relay
        container_name: relay
        build:
            context: .
            dockerfile: RelayServer/Dockerfile
        ports:
            - "50051:50051"
            - "8082:8082"